version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    commit-message:
      prefix: "Deps"
      prefix-development: "Dev"
